L07 — Ćwiczenia laboratoryjne
Temat: Pandas — czyszczenie danych
Programowanie w Pythonie II | Laboratorium 7 Czas: 90 min | Forma: ćwiczenia praktyczne

In [ ]:
import pandas as pd
import numpy as np

data = {
    'id_pracownika': [1,2,3,4,5,6,7,8,9,10,
                      11,12,13,14,15,16,17,18,19,20,
                      3,7,12,18,5, # duplikaty — te same id!
                      21,22,23,24,25],
    'imie': ['Anna', 'Bartek', 'CELINA', 'darek', 'Ewa',
             'Filip', 'Gosia', 'HENRYK', 'irena', 'Jan',
             'Kasia', 'Leszek', 'Marta', 'norbert', 'OLGA',
             'Piotr', 'Renata', 'sławek', 'Teresa', 'Urszula',
             'CELINA', 'Gosia', 'Leszek', 'sławek', 'Ewa',
             'Wanda', 'Xawery', 'Yvonne', 'Zbyszek', 'Agata'],
    'dzial': ['Sprzedaz', 'IT', 'HR', 'sprzedaz', 'IT',
              'HR', 'Sprzedaz', 'it', 'HR', 'Sprzedaz',
              'IT', 'HR', 'sprzedaz', 'IT', 'HR',
              'Sprzedaz', 'it', 'HR', 'data = {Sprzedaz', 'IT',
              'HR', 'Sprzedaz', 'HR', 'HR', 'IT',
              'Sprzedaz', 'IT', 'hr', 'Sprzedaz', 'IT'],
    'wynagrodzenie': ['4500', '6200', '3800', '5100', '7500',
                      '4200', '5800', '6900', '3500', '4800',
                      '7200', '4100', '5500', '6800', '3900',
                      '5200', '4700', '6100', '3800', '5400',
                      '3800', '5800', '4100', '6100', '7500',
                      'brak', '5000', None, '4300', '6600'],
    'data_zatrudnienia': ['2020-03-15', '2019-07-22', '2021-01-10',
                          '2018-05-30', '2022-11-01', '2020-08-14',
                          '2019-12-05', '2021-06-18', '2017-09-23',
                          '2023-02-07', '2020-04-11', '2018-11-28',
                          '2022-07-15', '2019-03-19', '2021-10-08',
                          '2020-06-25', '2018-08-31', '2022-02-14',
                          '2019-05-07', '2021-09-20', '2021-01-10',
                          '2019-12-05', '2018-11-28', '2022-02-14',
                          '2022-11-01', '2023-01-15', '2022-05-20',
                          None, '2020-10-11', '2019-08-03'],
    'ocena_roczna': [4.5, 3.8, None, 4.2, 5.0,
                     3.5, 4.7, None, 4.1, 3.9,
                     5.0, 4.3, 3.6, None, 4.8,
                     3.7, 4.4, 4.9, None, 3.8,
                     None, 4.7, 4.3, 4.9, 5.0,
                     4.6, None, 4.9, 3.5, 4.1]
}

df = pd.DataFrame(data)
print(f"Wczytano dataset: {df.shape[0]} wierszy, {df.shape[1]} kolumn")
df.head(10)

Wczytano dataset: 30 wierszy, 6 kolumn

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5
1,2,Bartek,IT,6200,2019-07-22,3.8
2,3,CELINA,HR,3800,2021-01-10,NaN
3,4,darek,sprzedaz,5100,2018-05-30,4.2
4,5,Ewa,IT,7500,2022-11-01,5.0
5,6,Filip,HR,4200,2020-08-14,3.5
6,7,Gosia,Sprzedaz,5800,2019-12-05,4.7
7,8,HENRYK,it,6900,2021-06-18,NaN
8,9,irena,HR,3500,2017-09-23,4.1
9,10,Jan,Sprzedaz,4800,2023-02-07,3.9

Ćwiczenie 1: Brakujące wartości (20 min)

Zadanie 1a — Diagnoza

In [2]:
# 1. Wyświetl info() aby zobaczyć typy danych i liczbę wartości non-null
df.info()
# 2. Policz brakujące wartości w każdej kolumnie (isna().sum())
braki_w_kolumnach = df.isna().sum()
print("Liczba braków w kolumnach:")
print(braki_w_kolumnach)
# 3. Oblicz procent braków per kolumna (zaokrąglij do 1 miejsca po przecinku)
procent_brakow = (df.isna().sum() / len(df)) * 100
procent_brakow_zaokraglony = procent_brakow.round(1)

print("Procent brakujących danych w kolumnach (%):")
print(procent_brakow_zaokraglony)
# 4. Wyświetl wiersze, które mają przynajmniej jeden brak (any(axis=1))
wiersze_z_brakami = df[df.isna().any(axis=1)]

print("Wiersze zawierające chociaż jeden brak danych:")
wiersze_z_brakami

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_pracownika      30 non-null     int64
 1   imie               30 non-null     str
 2   dzial              30 non-null     str
 3   wynagrodzenie      29 non-null     str
 4   data_zatrudnienia  29 non-null     str
 5   ocena_roczna       24 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 1.5 KB
Liczba braków w kolumnach:
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        1
data_zatrudnienia    1
ocena_roczna         6
dtype: int64
Procent brakujących danych w kolumnach (%):
id_pracownika         0.0
imie                  0.0
dzial                 0.0
wynagrodzenie         3.3
data_zatrudnienia     3.3
ocena_roczna         20.0
dtype: float64
Wiersze zawierające chociaż jeden brak danych:

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
2,3,CELINA,HR,3800,2021-01-10,NaN
7,8,HENRYK,it,6900,2021-06-18,NaN
13,14,norbert,IT,6800,2019-03-19,NaN
18,19,Teresa,Sprzedaz,3800,2019-05-07,NaN
20,3,CELINA,HR,3800,2021-01-10,NaN
26,22,Xawery,IT,5000,2022-05-20,NaN
27,23,Yvonne,hr,NaN,NaN,4.9

Zadanie 1b — Wynagrodzenie: 'brak' i None

In [6]:
# 1. Sprawdź unikalne wartości w kolumnie wynagrodzenie
# df['wynagrodzenie'].unique()
print(df['wynagrodzenie'].unique())

# 2. Zamień 'brak' na np.nan
# df['wynagrodzenie'] = df['wynagrodzenie'].replace('brak', np.nan)
df['wynagrodzenie'] = df['wynagrodzenie'].replace('brak', np.nan)

# 3. Skonwertuj wynagrodzenie na float używając pd.to_numeric z errors='coerce'
# df['wynagrodzenie'] = pd.to_numeric(df['wynagrodzenie'], errors='coerce')
df['wynagrodzenie'] = pd.to_numeric(df['wynagrodzenie'], errors='coerce')

# 4. Ile NaN jest teraz w wynagrodzenie?
print(df['wynagrodzenie'].isna().sum())

<StringArray>
['4500', '6200', '3800', '5100', '7500', '4200', '5800', '6900', '3500',
 '4800', '7200', '4100', '5500', '6800', '3900', '5200', '4700', '6100',
 '5400', 'brak', '5000',    nan, '4300', '6600']
Length: 24, dtype: str
2

Zadanie 1c — Strategie fillna

In [7]:
# 1. Oblicz medianę wynagrodzenia (ignorując NaN — to domyślne zachowanie)
# mediana = df['wynagrodzenie'].median()
# print(f"Mediana: {mediana}")
mediana = df['wynagrodzenie'].median()
print(f"Mediana: {mediana}")

# 2. Wypełnij NaN w wynagrodzeniu medianą
# df['wynagrodzenie'] = df['wynagrodzenie'].fillna(mediana)
df['wynagrodzenie'] = df['wynagrodzenie'].fillna(mediana)
# 3. Oblicz średnią ocena_roczna (zaokrąglij do 2 miejsc)
# srednia = round(df['ocena_roczna'].mean(), 2)
# print(f"Srednia ocena: {srednia}")
srednia = round(df['ocena_roczna'].mean(), 2)
print(f"Średnia ocena: {srednia}")

# 4. Wypełnij NaN w ocena_roczna średnią
# df['ocena_roczna'] = df['ocena_roczna'].fillna(srednia)
df['ocena_roczna'] = df['ocena_roczna'].fillna(srednia)

# 5. Sprawdź ile NaN zostało w każdej kolumnie
print(df.isna().sum())

Mediana: 5150.0
Średnia ocena: 4.34
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

Zadanie 1d — dropna

In [8]:
# 1. Ile wierszy zostanie po usunięciu wierszy z brakiem w 'data_zatrudnienia'?
# df_bez_brakow = df.dropna(subset=['data_zatrudnienia'])
# print(len(df_bez_brakow))
# Uwaga: NIE nadpisujemy df — tylko liczymy, ile wierszy by zostało
df_bez_brakow = df.dropna(subset=['data_zatrudnienia'])
print(len(df_bez_brakow))

29

Ćwiczenie 2: Duplikaty + konwersja typów (20 min)

In [9]:
# Zacznij od świeżej kopii
df2 = pd.DataFrame(data) # ta sama definicja 'data' co wyżej
# Najpierw napraw wynagrodzenie (tak samo jak w Ćw. 1b)
df2['wynagrodzenie'] = df2['wynagrodzenie'].replace('brak', np.nan)
df2['wynagrodzenie'] = pd.to_numeric(df2['wynagrodzenie'], errors='coerce')

Zadanie 2a — Wykrycie duplikatów

In [10]:
# 1. Ile pełnych duplikatów (identycznych wierszy) ma dataset?
# df2.duplicated().sum()
print(df2.duplicated().sum())
# 2. Wyświetl zduplikowane wiersze (te które są kopiami)
# df2[df2.duplicated()]
print(df2[df2.duplicated()])

# 3. Czy liczba duplikatów wg id_pracownika jest taka sama?
# df2.duplicated(subset=['id_pracownika']).sum()
print(df2.duplicated(subset=['id_pracownika']).sum())

# 4. Wyświetl ile razy pojawia się każde id_pracownika
# df2['id_pracownika'].value_counts().sort_index()
print(df2['id_pracownika'].value_counts().sort_index())

5
    id_pracownika    imie     dzial  wynagrodzenie data_zatrudnienia  \
20              3  CELINA        HR         3800.0        2021-01-10
21              7   Gosia  Sprzedaz         5800.0        2019-12-05
22             12  Leszek        HR         4100.0        2018-11-28
23             18  sławek        HR         6100.0        2022-02-14
24              5     Ewa        IT         7500.0        2022-11-01

    ocena_roczna
20           NaN
21           4.7
22           4.3
23           4.9
24           5.0
5
id_pracownika
1     1
2     1
3     2
4     1
5     2
6     1
7     2
8     1
9     1
10    1
11    1
12    2
13    1
14    1
15    1
16    1
17    1
18    2
19    1
20    1
21    1
22    1
23    1
24    1
25    1
Name: count, dtype: int64

Zadanie 2b — Usunięcie duplikatów

In [11]:
# 1. Usuń pełne duplikaty i zresetuj indeks
# df2 = df2.drop_duplicates().reset_index(drop=True)
df2 = df2.drop_duplicates().reset_index(drop=True)

# 2. Wyświetl nowy kształt DataFrame
# print(df2.shape)
print(df2.shape)

(25, 6)

Zadanie 2c — Konwersja daty

In [12]:
# 1. Sprawdź aktualny typ kolumny data_zatrudnienia
# print(df2['data_zatrudnienia'].dtype)
print(df2['data_zatrudnienia'].dtype)

# 2. Skonwertuj na datetime
# df2['data_zatrudnienia'] = pd.to_datetime(df2['data_zatrudnienia'], errors='coerce')
df2['data_zatrudnienia'] = pd.to_datetime(df2['data_zatrudnienia'], errors='coerce')
# 3. Sprawdź nowy typ
# print(df2['data_zatrudnienia'].dtype)
print(df2['data_zatrudnienia'].dtype)

# 4. Wyodrębnij rok zatrudnienia do nowej kolumny 'rok_zatrudnienia'
# df2['rok_zatrudnienia'] = df2['data_zatrudnienia'].dt.year
# print(df2['rok_zatrudnienia'].dropna().unique())
df2['rok_zatrudnienia'] = df2['data_zatrudnienia'].dt.year
print(df2['rok_zatrudnienia'].dropna().unique())

str
datetime64[us]
[2020. 2019. 2021. 2018. 2022. 2017. 2023.]

Zadanie 2d — Pytanie biznesowe

In [13]:
# Używając df2 po czyszczeniu:
# 1. Ile pracowników zostało zatrudnionych po 2021 roku (włącznie)?
print((df2['rok_zatrudnienia'] >= 2021).sum())

# 2. Ile pracowników ma wynagrodzenie powyżej 6000?
# Uwaga: najpierw wyczyść dzial — str.strip().str.title()
print((df2['wynagrodzenie'] > 6000).sum())
df2['dzial'] = df2['dzial'].str.strip().str.title()

# df2['dzial'] = df2['dzial'].str.strip().str.title()
# 3. Ilu pracowników jest w dziale 'It' (po title())?
print((df2['dzial'] == 'It').sum())

10
7
9

Ćwiczenie 3: Pełny pipeline czyszczenia (25 min)

In [14]:
df_clean = pd.DataFrame(data) # zacznij od świeżego df
# KROK 1: Zamień 'brak' na np.nan i skonwertuj wynagrodzenie na float
df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].replace('brak', np.nan)
df_clean['wynagrodzenie'] = pd.to_numeric(df_clean['wynagrodzenie'], errors='coerce')

# KROK 2: Usuń duplikaty (drop_duplicates) i zresetuj indeks
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

# KROK 3: Wypełnij NaN w wynagrodzeniu medianą (liczoną po usunięciu duplikatów)
mediana_wyn = df_clean['wynagrodzenie'].median()
df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].fillna(mediana_wyn)

# KROK 4: Oblicz średnią ocena_roczna i wypełnij NaN tą średnią (zaokrąglij do 2 miejsc)
srednia_ocen = round(df_clean['ocena_roczna'].mean(), 2)
df_clean['ocena_roczna'] = df_clean['ocena_roczna'].fillna(srednia_ocen)

# KROK 5: Wyczyść kolumnę 'imie': str.strip() + str.title()
df_clean['imie'] = df_clean['imie'].str.strip().str.title()

# KROK 6: Wyczyść kolumnę 'dzial':
# a) str.strip() + str.title()
df_clean['dzial'] = df_clean['dzial'].str.strip().str.title()
# b) str.replace('Hr', 'HR', regex=False)
df_clean['dzial'] = df_clean['dzial'].str.replace('Hr', 'HR', regex=False)
# c) str.replace('It', 'IT', regex=False)
df_clean['dzial'] = df_clean['dzial'].str.replace('It', 'IT', regex=False)

# KROK 7: Skonwertuj 'data_zatrudnienia' na datetime (errors='coerce')
df_clean['data_zatrudnienia'] = pd.to_datetime(df_clean['data_zatrudnienia'], errors='coerce')


# WERYFIKACJA — uruchom te linijki żeby sprawdzić wyniki:
print("=== WERYFIKACJA ===")
print(f"Shape: {df_clean.shape}")
print(f"\nDtypes:\n{df_clean.dtypes}")
print(f"\nNaN per kolumna:\n{df_clean.isna().sum()}")
print(f"\nUnikalne działy: {sorted(df_clean['dzial'].unique())}")
print(f"\nPierwsze imiona: {df_clean['imie'].tolist()[:8]}")

=== WERYFIKACJA ===
Shape: (25, 6)

Dtypes:
id_pracownika                 int64
imie                            str
dzial                           str
wynagrodzenie               float64
data_zatrudnienia    datetime64[us]
ocena_roczna                float64
dtype: object

NaN per kolumna:
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

Unikalne działy: ['HR', 'IT', 'Sprzedaz']

Pierwsze imiona: ['Anna', 'Bartek', 'Celina', 'Darek', 'Ewa', 'Filip', 'Gosia', 'Henryk']

Ćwiczenie 4: Operacje na tekstach + commit (10 min)

Zadanie 4a — Diagnoza przed czyszczeniem

In [16]:
df_str = pd.DataFrame(data) # świeża kopia
# 1. Ile imion jest zapisanych WSZYSTKIMI WIELKIMI LITERAMI?
# Wskazówka: str.isupper() zwraca True jeśli wszystkie litery wielkie
# df_str['imie'].str.isupper().sum()
print(df_str['imie'].str.isupper().sum())

# 2. Ile imion zaczyna się małą literą?
# Wskazówka: str[0].str.islower() — pierwsza litera
# df_str['imie'].str[0].str.islower().sum()
print(df_str['imie'].str[0].str.islower().sum())

# 3. Ile wierszy ma 'sprzedaz' w kolumnie dzial (niezależnie od wielkości)?
# Wskazówka: str.lower().str.contains('sprzedaz')
# df_str['dzial'].str.lower().str.contains('sprzedaz').sum()
print(df_str['dzial'].str.lower().str.contains('sprzedaz').sum())

4
5
10

Zadanie 4b — Czyszczenie i analiza

In [17]:
# 1. Wyczyść imie: strip() + title()
df_str['imie'] = df_str['imie'].str.strip().str.title()

# 2. Wyczyść dzial: strip() + title() + replace
df_str['dzial'] = df_str['dzial'].str.strip().str.title()
df_str['dzial'] = df_str['dzial'].str.replace('Hr', 'HR', regex=False)
df_str['dzial'] = df_str['dzial'].str.replace('It', 'IT', regex=False)

# 3. Ile pracowników ma imię zaczynające się na 'A'?
print((df_str['imie'].str.startswith('A')).sum())

# 4. Utwórz kolumnę 'dlugosc_imienia' z długością imienia
df_str['dlugosc_imienia'] = df_str['imie'].str.len()
print(df_str['dlugosc_imienia'].describe())

# 5. Kto ma najdłuższe imię? (nlargest lub sort_values)
print(df_str.nlargest(1, 'dlugosc_imienia')[['imie', 'dlugosc_imienia']])

2
count    30.000000
mean      5.333333
std       1.093345
min       3.000000
25%       5.000000
50%       5.500000
75%       6.000000
max       7.000000
Name: dlugosc_imienia, dtype: float64
       imie  dlugosc_imienia
13  Norbert                7

Zadanie 4c — str.contains z wzorcem

In [18]:
# str.contains() może używać wyrażeń regularnych!
# 1. Znajdź pracowników z działów IT lub HR (jeden zawiera drugi wzorzec)
# df_str[df_str['dzial'].str.contains('IT|HR')]
print(df_str[df_str['dzial'].str.contains('IT|HR')])

# 2. Znajdź imiona zawierające literę 'a' (małą lub dużą)
# df_str[df_str['imie'].str.contains('a', case=False)]
print(df_str[df_str['imie'].str.contains('a', case=False)])

# 3. Ile pracowników ma imię kończące się na 'a'?
# Wskazówka: str.endswith('a') lub str.contains('a$', regex=True)
print((df_str['imie'].str.endswith('a')).sum())

    id_pracownika     imie dzial wynagrodzenie data_zatrudnienia  \
1               2   Bartek    IT          6200        2019-07-22
2               3   Celina    HR          3800        2021-01-10
4               5      Ewa    IT          7500        2022-11-01
5               6    Filip    HR          4200        2020-08-14
7               8   Henryk    IT          6900        2021-06-18
8               9    Irena    HR          3500        2017-09-23
10             11    Kasia    IT          7200        2020-04-11
11             12   Leszek    HR          4100        2018-11-28
13             14  Norbert    IT          6800        2019-03-19
14             15     Olga    HR          3900        2021-10-08
16             17   Renata    IT          4700        2018-08-31
17             18   Sławek    HR          6100        2022-02-14
19             20  Urszula    IT          5400        2021-09-20
20              3   Celina    HR          3800        2021-01-10
22             12   Leszek    HR          4100        2018-11-28
23             18   Sławek    HR          6100        2022-02-14
24              5      Ewa    IT          7500        2022-11-01
26             22   Xawery    IT          5000        2022-05-20
27             23   Yvonne    HR           NaN               NaN
29             25    Agata    IT          6600        2019-08-03

    ocena_roczna  dlugosc_imienia
1            3.8                6
2            NaN                6
4            5.0                3
5            3.5                5
7            NaN                6
8            4.1                5
10           5.0                5
11           4.3                6
13           NaN                7
14           4.8                4
16           4.4                6
17           4.9                6
19           3.8                7
20           NaN                6
22           4.3                6
23           4.9                6
24           5.0                3
26           NaN                6
27           4.9                6
29           4.1                5
    id_pracownika     imie     dzial wynagrodzenie data_zatrudnienia  \
0               1     Anna  Sprzedaz          4500        2020-03-15
1               2   Bartek        IT          6200        2019-07-22
2               3   Celina        HR          3800        2021-01-10
3               4    Darek  Sprzedaz          5100        2018-05-30
4               5      Ewa        IT          7500        2022-11-01
6               7    Gosia  Sprzedaz          5800        2019-12-05
8               9    Irena        HR          3500        2017-09-23
9              10      Jan  Sprzedaz          4800        2023-02-07
10             11    Kasia        IT          7200        2020-04-11
12             13    Marta  Sprzedaz          5500        2022-07-15
14             15     Olga        HR          3900        2021-10-08
16             17   Renata        IT          4700        2018-08-31
17             18   Sławek        HR          6100        2022-02-14
18             19   Teresa  Sprzedaz          3800        2019-05-07
19             20  Urszula        IT          5400        2021-09-20
20              3   Celina        HR          3800        2021-01-10
21              7    Gosia  Sprzedaz          5800        2019-12-05
23             18   Sławek        HR          6100        2022-02-14
24              5      Ewa        IT          7500        2022-11-01
25             21    Wanda  Sprzedaz          brak        2023-01-15
26             22   Xawery        IT          5000        2022-05-20
29             25    Agata        IT          6600        2019-08-03

    ocena_roczna  dlugosc_imienia
0            4.5                4
1            3.8                6
2            NaN                6
3            4.2                5
4            5.0                3
6            4.7                5
8            4.1                5
9            3.9                3
10           5.0                5
12           3.6                5
14           4.8                4
16           4.4                6
17           4.9                6
18           NaN                6
19           3.8                7
20           NaN                6
21           4.7                5
23           4.9                6
24           5.0                3
25           4.6                5
26           NaN                6
29           4.1                5
16